// Cada entrada necesita lat/lng reales. Se ha priorizado lugares muy
// visitados (centros urbanos, plazas) porque suelen tener mejor cobertura
// de Mapillary que sitios remotos. Añade o quita entradas libremente.
const LANDMARKS = [
  { name: "Torre Eiffel", country: "Francia", category: "Arquitectura",
    lat: 48.8584, lng: 2.2945,
    fact: "Se construyó en 1889 para la Exposición Universal y en su día se pensó que sería temporal." },
  { name: "Museo Guggenheim", country: "España", category: "Arquitectura moderna",
    lat: 43.2688, lng: -2.9340,
    fact: "Su fachada de titanio, obra de Frank Gehry, transformó por completo la ciudad de Bilbao en los 90." },
  { name: "Puente Golden Gate", country: "Estados Unidos", category: "Ingeniería",
    lat: 37.8199, lng: -122.4783,
    fact: "Su color naranja internacional se eligió para que fuera visible entre la niebla de la bahía." },
  { name: "Cristo Redentor", country: "Brasil", category: "Monumento",
    lat: -22.9519, lng: -43.2105,
    fact: "La estatua corona el cerro Corcovado y mide unos 30 metros sin contar el pedestal." },
  { name: "Coliseo", country: "Italia", category: "Historia antigua",
    lat: 41.8902, lng: 12.4922,
    fact: "Podía albergar a más de 50.000 espectadores para combates de gladiadores." },
  { name: "Taj Mahal", country: "India", category: "Arquitectura",
    lat: 27.1751, lng: 78.0421,
    fact: "Fue construido por el emperador Shah Jahan como mausoleo para su esposa favorita." },
  { name: "Ópera de Sídney", country: "Australia", category: "Arquitectura moderna",
    lat: -33.8568, lng: 151.2153,
    fact: "Sus icónicas cubiertas curvas tardaron más de una década en construirse." },
  { name: "Sagrada Familia", country: "España", category: "Arquitectura",
    lat: 41.4036, lng: 2.1744,
    fact: "Antoni Gaudí dedicó más de 40 años a este templo, que sigue sin terminarse." },
  { name: "Estatua de la Libertad", country: "Estados Unidos", category: "Monumento",
    lat: 40.6892, lng: -74.0445,
    fact: "Fue un regalo de Francia a Estados Unidos, inaugurada en 1886." },
  { name: "Burj Khalifa", country: "Emiratos Árabes Unidos", category: "Arquitectura moderna",
    lat: 25.1972, lng: 55.2744,
    fact: "Con más de 828 metros, es el edificio más alto del mundo desde 2010." },
  { name: "Pirámides de Guiza", country: "Egipto", category: "Historia antigua",
    lat: 29.9792, lng: 31.1342,
    fact: "La Gran Pirámide fue la estructura más alta hecha por el hombre durante casi 3800 años." },
  { name: "Big Ben", country: "Reino Unido", category: "Arquitectura",
    lat: 51.5007, lng: -0.1246,
    fact: "El nombre corresponde en realidad a la campana principal, no a la torre entera." },
  { name: "Arco del Triunfo", country: "Francia", category: "Monumento",
    lat: 48.8738, lng: 2.2950,
    fact: "Bajo el arco descansa la Tumba del Soldado Desconocido desde 1921." },
  { name: "Puerta de Brandeburgo", country: "Alemania", category: "Monumento",
    lat: 52.5163, lng: 13.3777,
    fact: "Fue durante décadas un símbolo de la división de Berlín durante la Guerra Fría." },
  { name: "Fontana di Trevi", country: "Italia", category: "Arte",
    lat: 41.9009, lng: 12.4833,
    fact: "La tradición dice que lanzar una moneda garantiza volver a Roma." },
  { name: "Empire State Building", country: "Estados Unidos", category: "Arquitectura",
    lat: 40.7484, lng: -73.9857,
    fact: "Fue el edificio más alto del mundo durante casi 40 años tras su apertura en 1931." },
  { name: "Kremlin y Plaza Roja", country: "Rusia", category: "Historia",
    lat: 55.7520, lng: 37.6175,
    fact: "La Catedral de San Basilio, con sus cúpulas de colores, está justo al lado." },
  { name: "Puerta de Alcalá", country: "España", category: "Monumento",
    lat: 40.4200, lng: -3.6883,
    fact: "Es una de las puertas reales que daban acceso a Madrid, construida en el siglo XVIII." },
  { name: "Torre de Pisa", country: "Italia", category: "Arquitectura",
    lat: 43.7230, lng: 10.3966,
    fact: "Su inclinación se debe a un terreno inestable descubierto durante la propia construcción." },
  { name: "Mezquita Azul", country: "Turquía", category: "Arquitectura",
    lat: 41.0054, lng: 28.9768,
    fact: "Debe su apodo a los más de 20.000 azulejos azules de Iznik que decoran su interior." },
  { name: "Machu Picchu", country: "Perú", category: "Historia antigua",
    lat: -13.1631, lng: -72.5450,
    fact: "La ciudadela inca permaneció oculta entre montañas hasta su difusión internacional en 1911." },
  { name: "Petra", country: "Jordania", category: "Historia antigua",
    lat: 30.3285, lng: 35.4444,
    fact: "Sus fachadas fueron talladas directamente en roca rosada por los nabateos hace más de 2000 años." }
];
